### ISSUE TITLE
Ave as value 11?

### ISSUE THREAD

**Issue by jeff-minard-ck** [Marconiusiii/HitTheDeck#5]
Maybe I've missed it in the code, but can't an Ace be worth 11 _or_ 1?

**Comment by Marconiusiii** [comment]
Yes, and I have checks around in the code where an Ace can get drawn to establish whether or not it is set to a value of 1 or 11. In any of the Hit sequences, a card is drawn and if the initial value is 1, there is an evaluation checking that if the current hand value plus 11 doesn't go over 21, then the Ace is changed to 11 and added to the hand value. I may have missed a few of these checks in the code and will go over them.
